### ISSUE TITLE
React as a dependency instead of peerDependency

### ISSUE THREAD

**Issue by kylekampy** [civicsource/react-inline-confirm#2]
Hello!

Thanks for building this module! I am using it for a project now and it works great!

The only issue I have is the package size. By pulling in react as a dependency instead of a peer dependency it results in pulling down all of react when installing your module.

Just thought I would call your attention to this. I attempted to fix it myself, but ran into some strange issues that I didn't have the time to deal with. If I happen to get it fixed, I'll submit a PR. :)

**Comment by chadly** [comment]
I updated it to a peer dep and pushed to npm as v2.1.0
